apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-hub-uploads-pvc
  labels:
    app: automation-hub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-hub-outputs-pvc
  labels:
    app: automation-hub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automation-hub-data-pvc
  labels:
    app: automation-hub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
